/*
 * Publication content lives separately from rendering behavior so new work can
 * be added without navigating the filter, carousel, and card implementation.
 */
window.LDC_PUBLICATIONS = Object.freeze([
  {
    id: "bringing-data-to-life",
    title: "Bringing Data to Life: Designing Data Characters for the Emotional&nbsp;Self",
    summary: "A poster exploring how customizable data characters can help people represent and reflect on affective experiences.",
    authors: ["Diego Abarcar Calugay", "Isabella Amador", "Keke Wu"],
    labMembers: ["Diego Abarcar Calugay", "Isabella Amador", "Keke Wu"],
    venue: "IEEE VIS",
    year: 2026,
    type: "Poster",
    theme: "Affective",
    links: [
      { type: "poster", url: "assets/bringing-data-to-life-vis-2026-poster.pdf" },
      { type: "paper", url: "https://arxiv.org/pdf/2608.28780" },
    ],
    thumbnail: "assets/bringing-data-to-life-thumbnail-black-cropped.png",
    featuredImageScale: "0.9",
    archiveImageScale: "1",
    archiveThumbnailFit: "cover",
  },
  {
    id: "cognitive-accessibility-reveals",
    title: "What Cognitive Accessibility Reveals About Data Visualization",
    summary: "A paper that positions cognitive accessibility as a critical lens for reconsidering visualization theory and practice.",
    authors: ["Keke Wu", "Jinjuan Heidi Feng", "Jonathan Lazar"],
    labMembers: ["Keke Wu"],
    venue: "IEEE VIS",
    year: 2026,
    type: "Workshop Paper",
    theme: "Accessible",
    links: [
      { type: "paper", url: "https://arxiv.org/pdf/2608.17039" },
      { type: "web", url: "https://arxiv.org/html/2608.17039" },
      { type: "video", url: "" },
    ],
    thumbnail: "assets/cognitive-accessibility-lenses-black.png",
    thumbnailFit: "contain-dark",
    featuredImageScale: "1",
    archiveImageScale: "1.0",
  },
  {
    id: "made-to-feel",
    title: "Made to Feel: How Designers Bring Emotions into Affective Visualization",
    summary: "Interviews with 15 visualization practitioners explore how designers work with emotion, the strategies they use, and the ethical questions they encounter.",
    authors: ["Yixin Bai", "Ziyi Wang", "Keke Wu", "Fumeng Yang"],
    labMembers: ["Keke Wu"],
    venue: "IEEE VIS",
    year: 2026,
    type: "Short Paper",
    theme: "Affective",
    links: [
      { type: "paper", url: "https://arxiv.org/pdf/2607.01593" },
      { type: "web", url: "https://arxiv.org/abs/2607.01593" },
    ],
    thumbnail: "assets/made-to-feel-thumbnail-viewer.png",
    thumbnailFit: "contain",
    featuredImageScale: "1",
    featuredThumbnailWidth: "192px",
    archiveThumbnailFit: "contain",
    archiveImageScale: "1.2",
    archiveThumbnailBackground: "#f3f5f7",
  },
  {
    id: "charting-the-immersive-self",
    title: "Charting the Immersive Self: A Scoping Review of Immersive Personal Visualisation",
    summary: "A scoping review mapping immersive personal visualisation and its potential to reshape how people access, understand, and live with personal data.",
    authors: ["Thomas Davidson", "Zihan Dai", "Yalong Yang", "Emily Wall", "Keke Wu"],
    labMembers: ["Keke Wu"],
    featuredAuthorBreakBefore: "Yalong Yang",
    venue: "IEEE VIS",
    year: 2026,
    type: "Full Paper",
    theme: "Embodied",
    links: [{ type: "paper", url: "assets/charting-the-immersive-self-vis-2026.pdf" }],
    thumbnail: "assets/charting-the-immersive-self-thumbnail-dark-simple.png",
    thumbnailFit: "contain-dark",
    featuredImageScale: "1.16",
    featuredImageOffsetY: "3px",
    archiveThumbnailFit: "contain",
    archiveThumbnailBackground: "#000000",
    thumbnailBlendMode: "normal",
    archiveImageScale: "1.16",
    archiveImageOffsetY: "3px",
  },
  {
    id: "evaluating-behavior-change-interventions",
    title: "Evaluating Behavior Change Interventions for Responsible Data Science",
    summary: "A study with 12 data scientists evaluates how motivational stories and a fairness toolkit support responsible practices and fairer machine learning models.",
    authors: ["Ziwei Dong", "Keke Wu", "Leilani Battle", "Emily Wall"],
    labMembers: ["Keke Wu"],
    venue: "ACM CHI",
    year: 2026,
    type: "Full Paper",
    theme: "",
    links: [
      { type: "paper", url: "https://emilywall.github.io/media/papers/BCInterventionCHI26.pdf" },
      { type: "web", url: "https://dl.acm.org/doi/full/10.1145/3772318.3791566" },
    ],
    thumbnail: "assets/responsible-data-science-thumbnail-cool.png",
    thumbnailFit: "contain",
    featuredImageScale: "1",
    featuredThumbnailWidth: "192px",
    archiveThumbnailFit: "contain",
    archiveImageScale: "1",
    archiveThumbnailBackground: "#f3f5f7",
    thumbnailBlendMode: "normal",
  },
]);
